### ISSUE TITLE
[Request] Text-based QR codes

### ISSUE THREAD

**Issue by DanTheMan827** [thesouldemon/3DS-QR-Poster#9]
This would require a slight modification to the CSS of the 3dshacks subreddit...

```
.md pre>code {
    font-size: 1em;
    line-height: 1em;
    font-family: 'Courier New', monospace !important;
}
```

After that though, you could do text-based QR codes right in the comment

See [ASCII QR Code Creator](http://asciiqr.com/index.php?i=&t=http%3A%2F%2Freddit.com%2Fr%2F3dshacks) for example source code

**Comment by denali999** [comment]
At this point I'm only interested in images.
